name: Build & Push Dataflow Flex Template

on:
  push:
    branches:
      - main # o la rama que uses
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Build and Push Docker Image
        run: |
          IMAGE_BASE=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/docker-repo/dataflow
          TAG=${{ github.sha }}
          docker build -t $IMAGE_BASE:$TAG -t $IMAGE_BASE:latest .
          docker push $IMAGE_BASE --all-tags

      - name: Success message
        run: echo "✅ Build and push complete!"
